complexity:
  LongMethod:
    ignoreAnnotated:
      - Test
  TooManyFunctions:
    ignoreAnnotatedFunctions: [ 'Preview' ]

formatting:
  ImportOrdering:
    active: false # in favor of ktlint import ordering

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  ObjectPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    allowedNames: '.*Preview$'
